config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  get 'home/about' , 'home#about'
  devise_for :users

  resources :books
  resources :users,only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :books, dependent: :destroy
attachment :profile_image

validates :name, presence: true, length: { minimum: 2, maximum: 20 }
validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:edit, :update, :index, :show, :destroy]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
before_action :ensure_current_user, {only: [:edit,:update,:destroy]}

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @user = current_user
    @books = Book.all
  	@book = Book.find(params[:id])
    @newbook = Book.new

  end

  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       redirect_to @book, notice: "You have created book successfully"
    else
    @books = Book.all
    flash.now[:alert] = "error."
    render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to @book, notice: "Book was successfully update."
    else
    flash.now[:alert] = "error."
    render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
    redirect_to @book, notice: "Book was successfully destroyed."
    end
  end

 private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

     def  ensure_current_user
      @book = Book.find(params[:id])
     if @book.user_id != current_user.id
        redirect_to books_path
     end
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 before_action :authenticate_user!, except: [:top, :about,]
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :ensure_current_user, {only: [:edit,:update,:destroy]}

def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "You have updated user successfully."
    else render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def  ensure_current_user
       @user = User.find(params[:id])
    if @user.id != current_user.id
     redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newbook.html.erb
<h2>New book</h2>
<%= form_for(book) do |f| %>
<% if book.errors.any? %>
<div class=error>
<h4><%= book.errors.count %>error</h4>
　　<ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
<% end %>
  <h5>Title</h5>
  <%= f.text_field :title,class: "col-xs-12" %>
  <h5>Opinion</h5>
  <%= f.text_area :body,class: "col-xs-12" %>
  <nav>
  <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
  </nav>
<% end %>
</div>

app/views/books/edit.html.erb
<div class="row">

<h1>Editing Book</h1>
<%= form_for(@book, url: book_path(@book.id)) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title,class:"col-xs-12" %>
    <h4>Opinion</h4>

    <%= f.text_area :body,class:"col-xs-12" %>

  <nav>
     <%= f.submit 'Update Book',class: "col-xs-12 btn btn-primary" %>
  </nav>
　<% end %>

<%= link_to "Show",book_path(@book.id)%>
<%= link_to "Back",books_path %>

</div>

app/views/books/index.html.erb
<div class="row">
  <div class="col-xs-3">

<%= render 'users/userinfo', user: @user %>

<%= render 'books/newbook', book: @book %>

<div class="col-xs-9">
<h1>Books</h1>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
        <td>
          <%= link_to(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, fallback: "no_image.jpg", size: "40x40") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
    <% end %>
  </tbody>
</table>
</div>

app/views/books/show.html.erb
<div class="row">
<div class= "col-xs-3">

<%= render 'users/userinfo', user: @user %>

<%= render 'books/newbook', book: @newbook %>


<div class="col-xs-9">
<h2>Book detail</h2>
<table class="table">
    <tr>
        <td>
        <%= link_to (@book.user) do %>
        <%= attachment_image_tag(@book.user, :profile_image, fallback: "no_image.jpg", size: "40x40") %>
        <br>
        <%= @book.user.name %>
        <% end %>
        </td>
        <td><%= link_to @book.title, @book %></td>
        <td><%= @book.body%></td>
        <% if @book.user == current_user %>
        <td><%= link_to "Edit", edit_book_path(@book),class:"btn-sm btn-success" %></td>
        <td>
        <%= link_to "Destroy", book_path(@book), class:"btn-sm btn-danger destroy(@book)", method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
        <% end %>

    </tr>
</table>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <nav class='nav navbar-nav navbar-left'>
    <div class="tite">Bookers</div>
    </nav>
    <nav>
    <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li>
        <%= link_to 'Home', user_path(current_user.id),class:"glyphicon glyphicon-home" %>
      </li>
      <li>
        <%= link_to 'users', users_path, class: 'glyphicon glyphicon-user users' %>
      </li>
      <li>
        <%= link_to 'Books', books_path, class: 'glyphicon glyphicon-book books' %>
      </li>
      <li>
        <%= link_to "logout", destroy_user_session_path, method: :delete, method: :delete, class: 'glyphicon glyphicon-log-out logout' %>
      </li>

    <% else %>
      <li><%= link_to 'Home', root_path, class: 'glyphicon glyphicon-home home' %>
      </li>
      <li><%= link_to 'About', home_about_path, class: 'glyphicon glyphicon-link about' %>
      </li>
      <li><%= link_to "sign Up", new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %>
      </li>
      <li><%= link_to "login", new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %>
      </li>
    <% end %>
  </ul>
</nav>
</div>
</header>

      <div class="container">
      <p id="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <main>
      <div class="container">
      <%= flash[:notice] %>
      <%= flash.now[:alert] %>

        <%= yield %>
      </div>
    </main>
  <footer>
      <div class='row'>
        <div class='col-xs-3 col-xs-offset-9'>
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/_userinfo.html.erb
    <h2>User info</h2>
    <table class="table">
    <tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" ,format: 'no_image.jpg' %></tr>
      <tr>
      <th>name</th>
      <th><%= user.name %></th>
      </tr>
      <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
      </tr>
    </table>
      <%= link_to"",edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div class=error>
<h4><%= @user.errors.count %>error</h4>
　　<ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
<% end %>
  <h4>name</h4>
  <%= f.text_field :name %>
  <h4>image</h4>
  <%= f.attachment_field :profile_image %>
  <h4>introduction</h4>
  <%= f.text_area :introduction %>
  <br><%= f.submit 'Update User' %></br>
<% end %>

app/views/users/index.html.erb
    <div class="row">
    <div class= "col-xs-3">

<%= render 'users/userinfo', user: @user %>

<%= render 'books/newbook', book: @book %>




    <div class="col-xs-9">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg") %></td>
          <td><%= user.name %></td>
          <td><%= link_to 'Show', user_path(user.id) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-3">

<%= render 'users/userinfo', user: @user %>

<%= render 'books/newbook', book: @book %>


<div class="col-xs-9">
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
        <td>
          <%= link_to(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, fallback: "no_image.jpg", size: "40x40") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
    <% end %>
  </tbody>
</table>
</body>
</div>